### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by j00h0jin** [ga111o/flutter-toss-ui#1]
.

**Comment by j00h0jin** [comment]
1. account 내에 반복되는 부분을 위젯화하기 (private하게 사용하기 위해 widget 이름 앞에 underscore 추가하여 사용)

**Comment by j00h0jin** [comment]
2. 상당히 넓은 애뮬레이터를 사용하고 있음에도 불구하고 overflow가 생김 이를 해결하면 좋겠음
또한 계좌 옆에 버튼이 있는 경우 계좌명과 버튼 사이의 최소 간격이 있으면 좋겠음
![image](https://github.com/ga111o/flutter-toss-ui/assets/129518557/28463f99-9a8b-429a-8050-3bdcded2fdb9)

**Comment by j00h0jin** [comment]
debugShowCheckedModeBanner: false 를 추가하면 우상단의 debug 딱지 제거할 수 있음

**Comment by j00h0jin** [comment]
3. 바텀네비게이션바는 custom으로 만들어야 수정사항 적용이 조금 더 자유로움
flutter에서 제공하는 건 커스텀에 제약이 있는 것 같음

**Comment by j00h0jin** [comment]
개인적인 의견
main에 코드를 두지말고 home_view라던지 toss_home_view라던지 view.dart 파일을 하나 생성해서 

`  return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: HomeView(),
    );`
    
이런 식으로 두었으면 함

**Comment by j00h0jin** [comment]
4. header에서 별 모양 icon과 toss text가 leading과 title로 나누어져 있는데 간격을 위해 아래 코드를 사용한 것으로 보임

`titleSpacing: -13.0`

개인적으로는 leading에 한꺼번에 두거나 title에 두는 것이 좋아보임

leading에 둘 경우 leadingWidth 를 사용하여 leading 크기를 조절할 수 있음

**Comment by ga111o** [comment]
> 2. 상당히 넓은 애뮬레이터를 사용하고 있음에도 불구하고 overflow가 생김 이를 해결하면 좋겠음
> 또한 계좌 옆에 버튼이 있는 경우 계좌명과 버튼 사이의 최소 간격이 있으면 좋겠음
> ![image](https://github.com/ga111o/flutter-toss-ui/assets/129518557/28463f99-9a8b-429a-8050-3bdcded2fdb9)
> 


문제점: 텍스트와 버튼이 닿아서 오버플로우 발생

토스의 경우

![1709964194632.png](https://github.com/ga111o/flutter-toss-ui/assets/152472224/ca7a36a6-43fa-4009-9a0a-34956afd0a7b)
만약 화면 최소 너비를 강제로 줄이는 등의 방법으로 텍스트와 버튼이 닿게 되는 상황이 된다면 버튼이 아래로 내려감

```
Row(
mainAlign: spacebetween
children: [
  아이콘()
  텍스트()
  버튼()
])
```

같은 방식이 아닌,

아이콘과 텍스트는 왼쪽 정렬, 버튼은 오른쪽 정렬 하는 방식으로 이루어진 것 같음

**Comment by ga111o** [comment]
> 2. 상당히 넓은 애뮬레이터를 사용하고 있음에도 불구하고 overflow가 생김 이를 해결하면 좋겠음
> 또한 계좌 옆에 버튼이 있는 경우 계좌명과 버튼 사이의 최소 간격이 있으면 좋겠음
> ![image](https://github.com/ga111o/flutter-toss-ui/assets/129518557/28463f99-9a8b-429a-8050-3bdcded2fdb9)
> 


문제점: 텍스트와 버튼이 닿아서 오버플로우 발생

토스의 경우

![1709964194632.png](https://github.com/ga111o/flutter-toss-ui/assets/152472224/ca7a36a6-43fa-4009-9a0a-34956afd0a7b)
만약 화면 최소 너비를 강제로 줄이는 등의 방법으로 텍스트와 버튼이 닿게 되는 상황이 된다면 버튼이 아래로 내려감

```
Row(
mainAlign: spacebetween
children: [
  아이콘()
  텍스트()
  버튼()
])
```

같은 방식이 아닌,

아이콘과 텍스트는 왼쪽 정렬, 버튼은 오른쪽 정렬 하는 방식으로 이루어진 것 같음
이런 방식으로 다시 한 번 해볼클

**Comment by ga111o** [comment]
나머지 부분도 참고해서 내일까지 수정해봄

**Comment by j00h0jin** [comment]
![image](https://github.com/ga111o/flutter-toss-ui/assets/129518557/e99cd55a-c089-485c-8d2a-1cfa60f7665b)
반응형 시 button이 가운데로 가는 것이 의도한 것인지는 모르겠으나 좋은 UI인 것은 아닌 것 같다고 느낌

**Comment by j00h0jin** [comment]
![image](https://github.com/ga111o/flutter-toss-ui/assets/129518557/dfb24ef8-0092-4a79-bcf9-f91a741e7f51)
해당과 같은 코드에서 정수가 뭘 나타내는 건지 한번에 이해하기 힘든 느낌이 들었음
가독성 있게 코드를 수정하거나 불가피할 경우에는 주석을 활용하는 것이 좋아보임

**Comment by j00h0jin** [comment]
![image](https://github.com/ga111o/flutter-toss-ui/assets/129518557/d264f7ee-9463-46ea-a43b-dab3d7d795df)

애뮬레이터 상에서 appBar가 이상하게 보임
내가 implements PreferredSizeWidget 형태로 appBar를 사용해보지 않아서 자세히는 모르지만 수정이 필요해보임

전에 Appbar가 자연스럽게 변경되도록 하는 걸 원하는 것 같아보였는데 [sliverAppBar](https://api.flutter.dev/flutter/material/SliverAppBar-class.html)를 써보면 좋을 것 같다는 생각이 듦

**Comment by j00h0jin** [comment]
bottomNavigationBar의 각각의 아이콘을 클릭했을 때 다른 페이지로 이동되게 수정하면 좋을 것 같음, 각 화면의 temp view를 만들어서 이동할 수 있게끔 해줬으면 함

[ref](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html)

하지만 해당 페이지에도 네비게이션 바는 들어가야 함

조금 더 욕심이 있다면 navigation bar 상의 view 변경 시 transition 효과를 주어도 됨

**Comment by j00h0jin** [comment]
토스 뱅크 이자를 받는 부분은 이자를 받으면 사라지는 것으로 알고 있음

toss bank 이자 여부를 state로 관리해서 이자를 받게 되면 해당 라인은 지워지게끔 설계하면 더 좋을 것 같음

간단하게 이자를 받았는지의 여부를 bool로 저장하여 bool값에 따라 보이도록 코드를 짜주면 되겠음
아마 토스의 경우 이자를 받는 페이지로 가서 버튼을 누르게 될텐데 해당 버튼을 누를 때 bool을 true로 변경해주고 메인으로 돌아가게 한다면 main으로 갔을 때의 이자 여부는 true이므로 이자 받는 widget이 보이지 않게 해주면 됨

**Comment by j00h0jin** [comment]
account.dart 안에서 widget화 해주는 건 좋았음
AccountLine이 해당 파일 안에서만 사용할 수 있게 underscore(_AccountLine)을 붙여서 private 하게 사용했으면 좋겠음

그리고 해당 widget에 required한 요소가 다소 많다고 생각이 듦
icon, bgColor, iconColor를 사용하지 않고 svg나 png를 받아서 asset을 사용하는 것도 요소를 줄일 수 있는 방법이 될 수 있음

또는 required를 지우고 default값을 설정하는 것도 방법이 될 수 있음
특히 getButton 요소의 경우에는 '이자 받기' 딱 하나에만 true가 되는 것으로 보이는데 이러한 경우에는 특히 적용하는 것이 적합할 수 있다고 봄

**Comment by j00h0jin** [comment]
디자인적인 측면이긴 하지만 핸드폰 앱을 만드는 것이기 때문에 보편적으로 애뮬레이터에서 폰트 크기를 봐주는 것이 좋다고 생각함
내가 테스트하는 애뮬레이터의 크기가 상당히 큰 편임에도 불구하고 overflow가 난다는 것은 앱의 전체적인 폰트 크기가 크다는 것임
따라서 전체적으로 폰트 크기를 줄이는 것이 좋아보임

**Comment by j00h0jin** [comment]
overflow시 row에서 column으로 변경하는 로직을 사용하였는데 [wrap](https://api.flutter.dev/flutter/widgets/Wrap-class.html)이라는 class를 사용하면 동일 기능을 조금 더 간결한 코드로 작성할 수 있음

**Comment by ga111o** [comment]
1, 8. 버튼 문제
-> wrap 하다가 안돼서 이런 방식 사용함. 다시 한 번 해봄

2. 코드 가독성
-> 가독성, 주석 신경 써봄


3. 앱 바 문제
-> 내 환경에서는 멀쩡했음
내가 웹으로 돌려서 그런 거일 수도 있고 다른 문제가 있을 수도 있고.. 함 찾아봐야 할 거 같음



4, 5. 화면 이동, 토스뱅크 이자 받기
-> 아직 안배웠어요..
배워야 할 것들이 내가 생각한 거랑 결이 많이 다르면 며칠 걸릴 수도


6, 7
적용해볼클

**Comment by ga111o** [comment]
1, 8. 버튼 문제
-> wrap 하다가 안돼서 이런 방식 사용함. 다시 한 번 해봄


2. 코드 가독성
-> 가독성, 주석 신경 써봄


3. 앱 바 문제
-> 내 환경에서는 멀쩡했음
내가 웹으로 돌려서 그런 거일 수도 있고 다른 문제가 있을 수도 있고.. 함 찾아봐야 할 거 같음


4, 5. 화면 이동, 토스뱅크 이자 받기
-> 아직 안배웠어요..
배워야 할 것들이 내가 생각한 거랑 결이 많이 다르면 며칠 걸릴 수도


6, 7
적용해볼클

**Comment by j00h0jin** [comment]
![image](https://github.com/ga111o/flutter-toss-ui/assets/129518557/2b7d81f4-f9a9-4078-9f2c-7dea225d0194)
해당 부분은 수정하지말고 참고만 하면 좋겠음
위 사진에서 사용한 예시처럼 amount같이 숫자만 받아올 확률이 높은 경우 int형으로 받아와서 format을 변형해주는 방식이 더 바람직함 (Api 연동 시를 고려)
[ref](https://dev-nam.tistory.com/27)

**Comment by ga111o** [comment]
> 토스 뱅크 이자를 받는 부분은 이자를 받으면 사라지는 것으로 알고 있음
> 
> toss bank 이자 여부를 state로 관리해서 이자를 받게 되면 해당 라인은 지워지게끔 설계하면 더 좋을 것 같음
> 
> 간단하게 이자를 받았는지의 여부를 bool로 저장하여 bool값에 따라 보이도록 코드를 짜주면 되겠음 아마 토스의 경우 이자를 받는 페이지로 가서 버튼을 누르게 될텐데 해당 버튼을 누를 때 bool을 true로 변경해주고 메인으로 돌아가게 한다면 main으로 갔을 때의 이자 여부는 true이므로 이자 받는 widget이 보이지 않게 해주면 됨

```dart
// Account 클래스

return Column(
  children: [
    if (이자) _AccountLine( name: '토스 이자 받기', 이자받기버튼: true),
  ])
```

```dart
// _AccountLine 클래스
int 이자= 1;

void 이자받기() { 이자 = 0; }

return Container(
  if (이자받기버튼) ? IconButton( onClick: 이자받기 ) : null
)
```

이런 식으로 작성했는데
_AccountLine에 있는 `이자`라는 변수를 Account로 보내는 거에서 막혀서 하루 종일 삽질만 함..
힌트 있나요

**Comment by ga111o** [comment]
> > 토스 뱅크 이자를 받는 부분은 이자를 받으면 사라지는 것으로 알고 있음
> > toss bank 이자 여부를 state로 관리해서 이자를 받게 되면 해당 라인은 지워지게끔 설계하면 더 좋을 것 같음
> > 간단하게 이자를 받았는지의 여부를 bool로 저장하여 bool값에 따라 보이도록 코드를 짜주면 되겠음 아마 토스의 경우 이자를 받는 페이지로 가서 버튼을 누르게 될텐데 해당 버튼을 누를 때 bool을 true로 변경해주고 메인으로 돌아가게 한다면 main으로 갔을 때의 이자 여부는 true이므로 이자 받는 widget이 보이지 않게 해주면 됨
> 
> ```dart
> // Account 클래스
> 
> return Column(
>   children: [
>     if (이자) _AccountLine( name: '토스 이자 받기', 이자받기버튼: true),
>   ])
> ```
> 
> ```dart
> // _AccountLine 클래스
> int 이자= 1;
> 
> void 이자받기() { 이자 = 0; }
> 
> return Container(
>   if (이자받기버튼) ? IconButton( onClick: 이자받기 ) : null
> )
> ```
> 
> 이런 식으로 작성했는데 _AccountLine에 있는 `이자`라는 변수를 Account로 보내는 거에서 막혀서 하루 종일 삽질만 함.. 힌트 있나요

provider라는 거 사용해서 구현 했어요

**Comment by j00h0jin** [comment]
> > > 토스 뱅크 이자를 받는 부분은 이자를 받으면 사라지는 것으로 알고 있음
> > > toss bank 이자 여부를 state로 관리해서 이자를 받게 되면 해당 라인은 지워지게끔 설계하면 더 좋을 것 같음
> > > 간단하게 이자를 받았는지의 여부를 bool로 저장하여 bool값에 따라 보이도록 코드를 짜주면 되겠음 아마 토스의 경우 이자를 받는 페이지로 가서 버튼을 누르게 될텐데 해당 버튼을 누를 때 bool을 true로 변경해주고 메인으로 돌아가게 한다면 main으로 갔을 때의 이자 여부는 true이므로 이자 받는 widget이 보이지 않게 해주면 됨
> > 
> > 
> > ```dart
> > // Account 클래스
> > 
> > return Column(
> >   children: [
> >     if (이자) _AccountLine( name: '토스 이자 받기', 이자받기버튼: true),
> >   ])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```dart
> > // _AccountLine 클래스
> > int 이자= 1;
> > 
> > void 이자받기() { 이자 = 0; }
> > 
> > return Container(
> >   if (이자받기버튼) ? IconButton( onClick: 이자받기 ) : null
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 이런 식으로 작성했는데 _AccountLine에 있는 `이자`라는 변수를 Account로 보내는 거에서 막혀서 하루 종일 삽질만 함.. 힌트 있나요
> 
> provider라는 거 사용해서 구현 했어요

이 코드 적용되어 있는 사항 브랜치 따로 파서 깃헙에 올려줘
나도 riverpod만 써보고 provider은 안써봐서 전체 코드 봐야할 것 같아

**Comment by ga111o** [comment]
> 같아

https://github.com/ga111o/flutter-toss-ui/tree/provider
provider가 사용된 파일들만 `provider`라는 branch에 commit 하긴 했는데
commit한 코드들만 보이는 게 아니라 이전까지 main branch에 commit된 코드들도 같이 보이네
아직까지 어케 사용하는지 잘 모르겠음..

```
class CounterClass {
  int _count = 0;
  void plus() { _count++ };
}

class Test {
  int counter = Provider.of<CounterClass>(context); // Provider 이용해서 Counter 인스턴스에 접근
  return Text('$counter')
}

void main{
  body(
    Button(
      onPressed: () {
        Provider.of<CounterClass>(context, listen: false).plus() 
  }))
}
```
일단 코드만 보면 이런 느낌?

**Comment by j00h0jin** [comment]
> > 같아
> 
> https://github.com/ga111o/flutter-toss-ui/tree/provider provider가 사용된 파일들만 `provider`라는 branch에 commit 하긴 했는데 commit한 코드들만 보이는 게 아니라 이전까지 main branch에 commit된 코드들도 같이 보이네 아직까지 어케 사용하는지 잘 모르겠음..
> 
> ```
> class CounterClass {
>   int _count = 0;
>   void plus() { _count++ };
> }
> 
> class Test {
>   int counter = Provider.of<CounterClass>(context); // Provider 이용해서 Counter 인스턴스에 접근
>   return Text('$counter')
> }
> 
> void main{
>   body(
>     Button(
>       onPressed: () {
>         Provider.of<CounterClass>(context, listen: false).plus() 
>   }))
> }
> ```
> 
> 일단 코드만 보면 이런 느낌?

원래 main에서 분기되는 거라 main에서 변경되지 않은 코드들도 적용되니까 보이는 게 맞아

일단 provider가 main보다는 homeView에 코드가 있는 게 좋을 것 같아 보여
그리고 class명과 파일명을 일치시켜주는 것이 좋아 homeView class가 있는 파일은 home_view.dart 이런 식으로

**Comment by j00h0jin** [comment]
> _AccountLine에 있는 `이자`라는 변수를 Account로 보내는 거에서

그리고 지금 코드들이 account에 있는데 widget에서는 상태관리를 해주는 것이 좋지 않은 코드 스타일이 될 수 있어
웬만하면 widget이 들어가있는 view에서 상태관리를 해주는 것이 좋을 것 같아

왜냐고 물어보면 조금 복잡해서 일단 widget에서 상태 관리를 하는 것은 그렇게 좋은 코드는 아니구나 생각하면 될 것 같아
좀 더 궁금하면 [안드로이드 아키텍처](https://developer.android.com/topic/architecture?hl=ko)에 관해 구글링 해봐도 좋아


provider는 내가 사용해보지 않아서 잘 몰라서 찾아는 봤는데 정확히 맞는 건지는 잘 모르겠네
notifyListeners()로 상태가 변경됐다고 알려주는 방식을 사용하는 것 같은데 한번 참고하면 될 것 같아

해당 코드에서는 이자 받기를 누를 때 onTap나 onPressed 같은 동작에 notifyListeners()를 넣어주면 될 것 같긴 한데 한번 해보고 안되면 다시 말해줘

**Comment by j00h0jin** [comment]
그리고 이 이슈까지 끝나면 해당 이슈는 닫고 새로 이슈파서 진행할게
코멘트가 많아서 다른 이슈를 파는 게 더 나을 것 같아

**Comment by ga111o** [comment]
> > _AccountLine에 있는 `이자`라는 변수를 Account로 보내는 거에서
> 
> 그리고 지금 코드들이 account에 있는데 widget에서는 상태관리를 해주는 것이 좋지 않은 코드 스타일이 될 수 있어 웬만하면 widget이 들어가있는 view에서 상태관리를 해주는 것이 좋을 것 같아
> 
> 왜냐고 물어보면 조금 복잡해서 일단 widget에서 상태 관리를 하는 것은 그렇게 좋은 코드는 아니구나 생각하면 될 것 같아 좀 더 궁금하면 [안드로이드 아키텍처](https://developer.android.com/topic/architecture?hl=ko)에 관해 구글링 해봐도 좋아
> 
> provider는 내가 사용해보지 않아서 잘 몰라서 찾아는 봤는데 정확히 맞는 건지는 잘 모르겠네 notifyListeners()로 상태가 변경됐다고 알려주는 방식을 사용하는 것 같은데 한번 참고하면 될 것 같아
> 
> 해당 코드에서는 이자 받기를 누를 때 onTap나 onPressed 같은 동작에 notifyListeners()를 넣어주면 될 것 같긴 한데 한번 해보고 안되면 다시 말해줘

코드 분리해놨는데 account.dart에서 분리해놓은 코드 삭제하는 거 깜박했어요

```
// models/foundation.dart

class InterestModel extends ChangeNotifier {
  int _getInterest = 1;

  int get getInterest => _getInterest;

  void getInterestFunc() {
    _getInterest = 0;
    notifyListeners();
  }
}
```
이렇게 관리하고 있어요

**Comment by j00h0jin** [comment]
> > > _AccountLine에 있는 `이자`라는 변수를 Account로 보내는 거에서
> > 
> > 
> > 그리고 지금 코드들이 account에 있는데 widget에서는 상태관리를 해주는 것이 좋지 않은 코드 스타일이 될 수 있어 웬만하면 widget이 들어가있는 view에서 상태관리를 해주는 것이 좋을 것 같아
> > 왜냐고 물어보면 조금 복잡해서 일단 widget에서 상태 관리를 하는 것은 그렇게 좋은 코드는 아니구나 생각하면 될 것 같아 좀 더 궁금하면 [안드로이드 아키텍처](https://developer.android.com/topic/architecture?hl=ko)에 관해 구글링 해봐도 좋아
> > provider는 내가 사용해보지 않아서 잘 몰라서 찾아는 봤는데 정확히 맞는 건지는 잘 모르겠네 notifyListeners()로 상태가 변경됐다고 알려주는 방식을 사용하는 것 같은데 한번 참고하면 될 것 같아
> > 해당 코드에서는 이자 받기를 누를 때 onTap나 onPressed 같은 동작에 notifyListeners()를 넣어주면 될 것 같긴 한데 한번 해보고 안되면 다시 말해줘
> 
> 코드 분리해놨는데 account.dart에서 분리해놓은 코드 삭제하는 거 깜박했어요
> 
> ```
> // models/foundation.dart
> 
> class InterestModel extends ChangeNotifier {
>   int _getInterest = 1;
> 
>   int get getInterest => _getInterest;
> 
>   void getInterestFunc() {
>     _getInterest = 0;
>     notifyListeners();
>   }
> }
> ```
> 
> 이렇게 관리하고 있어요

지금 확인해보니까 매우 괜찮네
여기서 이자받기 버튼이 비활성화된 시점부터 20초 뒤에 다시 활성화되도록 기능 추가해줘 
방법이야 많겠지만 나라면 Timer를 쓸 것 같아
참고로 Timer가 중복으로 생성되면 리소스를 크게 잡아먹으므로 항상 Timer는 하나만 생성되어 있어야 해 
이것만 하고 이슈 닫을게

**Comment by ga111o** [comment]
> 
> 지금 확인해보니까 매우 괜찮네 여기서 이자받기 버튼이 비활성화된 시점부터 20초 뒤에 다시 활성화되도록 기능 추가해줘 방법이야 많겠지만 나라면 Timer를 쓸 것 같아 참고로 Timer가 중복으로 생성되면 리소스를 크게 잡아먹으므로 항상 Timer는 하나만 생성되어 있어야 해 이것만 하고 이슈 닫을게

```
  void getInterestFunc() {
    _getInterest = 0;
    notifyListeners();
    Timer(const Duration(seconds: 2), () {
      _getInterest = 1;
      notifyListeners();
    });
  }
```
나오는 거 바로 확인하려고 2초로 함
너무 날먹한 거 같은데 이거 의도한 거 맞음?

**Comment by j00h0jin** [comment]
> > 지금 확인해보니까 매우 괜찮네 여기서 이자받기 버튼이 비활성화된 시점부터 20초 뒤에 다시 활성화되도록 기능 추가해줘 방법이야 많겠지만 나라면 Timer를 쓸 것 같아 참고로 Timer가 중복으로 생성되면 리소스를 크게 잡아먹으므로 항상 Timer는 하나만 생성되어 있어야 해 이것만 하고 이슈 닫을게
> 
> ```
>   void getInterestFunc() {
>     _getInterest = 0;
>     notifyListeners();
>     Timer(const Duration(seconds: 2), () {
>       _getInterest = 1;
>       notifyListeners();
>     });
>   }
> ```
> 
> 나오는 거 바로 확인하려고 2초로 함 너무 날먹한 거 같은데 이거 의도한 거 맞음?

기존에 생성된 Timer가 남아있을 수 있기 때문에 Timer가 쌓이면 쌓일수록 리소스가 낭비 돼
기존에 생성된 Timer가 있는지 확인하고 있으면 종료시키는 로직만 추가하면 될듯
